language: node_js
node_js:
  - "stable"

addons:
  chrome: stable

before_install:
  - npm install -g @lhci/cli@0.3.x


cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
  - lhci autorun --upload.target=temporary-public-storage

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN
  local_dir: build
  on:
    branch: dev
