# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
env:
    NODE_VERSION: '14.15.4'                # set this to the node version to use
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
          # Container registry username
          username: ${{ secrets.REGISTRY_USERNAME }}
          # Container registry password
          password: ${{ secrets.REGISTRY_PASSWORD }}
          # Container registry server url
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}  
    - run: |
          # building creating a new image tags for version control
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/devmycampus:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/devmycampus:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/devmycampus:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/devmycampus:latest
